apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal-app
  template:
    metadata:
      labels:
        app: minimal-app
    spec:
      containers:
      - name: minimal-container
        image: busybox
        command: ["echo", "Hello World from Kubernetes Minimal!"]
